apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fluxo-caixa
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Se seu cluster tiver StorageClass específica, descomente e ajuste:
  # storageClassName: local-path

