apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxo-caixa-app
  namespace: fluxo-caixa
  labels:
    app: fluxo-caixa-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluxo-caixa-app
  template:
    metadata:
      labels:
        app: fluxo-caixa-app
    spec:
      containers:
      - name: app
        # IMPORTANTE: Substituir pela sua imagem após build
        # Exemplo: seu-registry/fluxo-caixa-app:v1.0
        image: seu-registry/fluxo-caixa-app:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      # Init container para aguardar o PostgreSQL estar pronto
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']

