apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxo-caixa-app
  namespace: fluxo-caixa
  labels:
    app: fluxo-caixa
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluxo-caixa
      tier: backend
  template:
    metadata:
      labels:
        app: fluxo-caixa
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: app
          image: phfldocker/fluxo-caixa-app:v1.0
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

