apiVersion: v1
kind: ResourceQuota
metadata:
  name: fluxo-caixa-quota
  namespace: fluxo-caixa
spec:
  hard:
    # Limites de recursos
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    
    # Limites de storage
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    
    # Limites de objetos
    pods: "20"
    services: "10"
    configmaps: "10"
    secrets: "10"
    
    # Limites de serviços
    services.loadbalancers: "0"
    services.nodeports: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fluxo-caixa-limits
  namespace: fluxo-caixa
spec:
  limits:
  # Limites para containers
  - type: Container
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
  
  # Limites para PVCs
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi

