apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: fluxo-caixa
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres-service:5432/fluxocaixa?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: fluxo-caixa
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-exporter-secret
                  key: DATA_SOURCE_NAME
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: "/etc/postgres_exporter/queries.yaml"
          volumeMounts:
            - name: queries
              mountPath: /etc/postgres_exporter
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9187
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: queries
          configMap:
            name: postgres-exporter-queries
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-queries
  namespace: fluxo-caixa
data:
  queries.yaml: |
    # Custom queries for fluxocaixa database
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
      master: true
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size:
            usage: "GAUGE"
            description: "Disk space used by the database"
    
    pg_stat_user_tables:
      query: "SELECT schemaname, relname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del FROM pg_stat_user_tables"
      master: true
      metrics:
        - schemaname:
            usage: "LABEL"
            description: "Name of the schema"
        - relname:
            usage: "LABEL"
            description: "Name of the table"
        - seq_scan:
            usage: "COUNTER"
            description: "Number of sequential scans"
        - seq_tup_read:
            usage: "COUNTER"
            description: "Number of tuples read by sequential scans"
        - idx_scan:
            usage: "COUNTER"
            description: "Number of index scans"
        - idx_tup_fetch:
            usage: "COUNTER"
            description: "Number of tuples fetched by index scans"
        - n_tup_ins:
            usage: "COUNTER"
            description: "Number of tuples inserted"
        - n_tup_upd:
            usage: "COUNTER"
            description: "Number of tuples updated"
        - n_tup_del:
            usage: "COUNTER"
            description: "Number of tuples deleted"
    
    pg_stat_statements:
      query: "SELECT queryid, query, calls, total_exec_time, mean_exec_time, rows FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 20"
      master: true
      metrics:
        - queryid:
            usage: "LABEL"
            description: "Query ID"
        - query:
            usage: "LABEL"
            description: "Query text"
        - calls:
            usage: "COUNTER"
            description: "Number of times executed"
        - total_exec_time:
            usage: "COUNTER"
            description: "Total execution time"
        - mean_exec_time:
            usage: "GAUGE"
            description: "Mean execution time"
        - rows:
            usage: "COUNTER"
            description: "Total rows retrieved or affected"
    
    fluxocaixa_transactions:
      query: "SELECT tipo, status, COUNT(*) as count, COALESCE(SUM(valor), 0) as total_valor FROM transacoes GROUP BY tipo, status"
      master: true
      metrics:
        - tipo:
            usage: "LABEL"
            description: "Transaction type (receita/despesa)"
        - status:
            usage: "LABEL"
            description: "Transaction status"
        - count:
            usage: "GAUGE"
            description: "Number of transactions"
        - total_valor:
            usage: "GAUGE"
            description: "Total value of transactions"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: fluxo-caixa
  labels:
    app: postgres-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app: postgres-exporter

